# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wtyczka_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Projekt2DialogBase(object):
    def setupUi(self, Projekt2DialogBase):
        Projekt2DialogBase.setObjectName("Projekt2DialogBase")
        Projekt2DialogBase.resize(750, 511)
        self.buttonbox_okcancel = QtWidgets.QDialogButtonBox(Projekt2DialogBase)
        self.buttonbox_okcancel.setGeometry(QtCore.QRect(370, 460, 341, 32))
        self.buttonbox_okcancel.setOrientation(QtCore.Qt.Horizontal)
        self.buttonbox_okcancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonbox_okcancel.setObjectName("buttonbox_okcancel")
        self.maplayer_layer = QgsMapLayerComboBox(Projekt2DialogBase)
        self.maplayer_layer.setGeometry(QtCore.QRect(150, 170, 451, 51))
        self.maplayer_layer.setObjectName("maplayer_layer")
        self.label_liczba_elementow = QtWidgets.QLabel(Projekt2DialogBase)
        self.label_liczba_elementow.setGeometry(QtCore.QRect(340, 260, 151, 20))
        self.label_liczba_elementow.setObjectName("label_liczba_elementow")
        self.pushbutton_policz = QtWidgets.QPushButton(Projekt2DialogBase)
        self.pushbutton_policz.setGeometry(QtCore.QRect(330, 320, 93, 28))
        self.pushbutton_policz.setObjectName("pushbutton_policz")

        self.retranslateUi(Projekt2DialogBase)
        self.buttonbox_okcancel.accepted.connect(Projekt2DialogBase.accept) # type: ignore
        self.buttonbox_okcancel.rejected.connect(Projekt2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Projekt2DialogBase)

    def retranslateUi(self, Projekt2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        Projekt2DialogBase.setWindowTitle(_translate("Projekt2DialogBase", "Naszawtyczka"))
        self.label_liczba_elementow.setText(_translate("Projekt2DialogBase", "TextLabel"))
        self.pushbutton_policz.setText(_translate("Projekt2DialogBase", "Policz"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Projekt2DialogBase = QtWidgets.QDialog()
    ui = Ui_Projekt2DialogBase()
    ui.setupUi(Projekt2DialogBase)
    Projekt2DialogBase.show()
    sys.exit(app.exec_())
